apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80               # Exposed port for external access
    targetPort: 8000       # Port on which the FastAPI app is running in the container
  selector:
    app: fastapi           # Matches the label in the deployment
