apiVersion: v1
kind: Service
metadata:
  name: fastapi-api-service
spec:
  type: LoadBalancer  # LoadBalancer or ClusterIP
  ports:
  - port: 80  # External port
    targetPort: 8000  # Port your app listens on (container port)
  selector:
    app: fastapi
