name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t fastapi-app:latest .
        docker tag fastapi-app:latest mdriyazali254362028/fastapi-app:latest
        docker push mdriyazali254362028/fastapi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

    - name: Apply Kubernetes deployment and service
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
