name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t fastapi-app:latest .
        docker tag fastapi-app:latest mdriyazali254362028/fastapi-app:latest
        docker push mdriyazali254362028/fastapi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the build job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Minikube (ensure connection to local Kubernetes cluster)
      run: |
        echo "Setting up Minikube..."
        minikube start
        eval $(minikube -p minikube docker-env)  # Set up Docker to use Minikube's Docker daemon

    - name: Set kubeconfig (to interact with Minikube cluster)
      run: |
        mkdir -p ~/.kube
        cp /home/runner/.minikube/config ~/.kube/config  # Ensure kubeconfig is set correctly
        kubectl config use-context minikube

    - name: Apply Kubernetes deployment and service
      run: |
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
